config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :chatrooms, only: [:show, :new, :create] do
    resources :messages, only: :create
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :events do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:edit, :update, :destroy]
  get 'dashboard', to: 'dashboard#dashboard'
  get 'conversations', to: 'conversations#conversations'
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def dashboard

  end
end

app/views/dashboard/dashboard.html.erb
<div class="page-container" data-controller="switch-tab">
  <div class="page-title"><h1>Welcome Back <%= current_user.first_name %>!</h1></div>

  <div>
    <ul class="list-inline tabs-underlined">
    <li>
      <a href="#" class="tab-underlined  <%= params[:classeventtab]%>" data-action="click->switch-tab#showEvents" data-switch-tab-target="event">My event</a>
    </li>
    <li>
      <a href="#" class="tab-underlined <%= params[:classbooktab]%>" data-action="click->switch-tab#showBookings" data-switch-tab-target="booking">My booking</a>
    </li>
    </ul>
  <div>

  <div class=" events-container <%= params[:classevent] %>" data-switch-tab-target="events">
  <h5>There are <%= current_user.events.count %> coming <%='event'.pluralize(current_user.events.count) %><i class="fa-solid fa-bullhorn"></i></h5>
      <% current_user.events.each do |event|  %>
      <div class="dashboard-item">

        <div class="item-description">
        <div>
          <%  if event.photo.key.nil? %>
            <%= image_tag "placeholder-image.png", crop: :fill,  class: "event-img-vertical-s" %>
          <% else  %>
            <%= cl_image_tag event.photo.key, crop: :fill,  class: "event-img-vertical-s" %>
          <% end  %>
        </div>

        <div class="flex-group">
          <div>
            <div><h5><%= event.event_name %></h5></div>
            <div><span><%= event.sport %></span></div>
            <div><span><%= event.date.strftime(' %m-%b-%Y (%a)') %><strong> · </strong>
            <%= event.duration %><strong> · </strong><%= event.level %></span></div>
          </div>

          <div class="icon-group">
          <div class="icon"><%= link_to '', event_path(event.id), class:'fa-solid fa-magnifying-glass'%></div>
          <div class="icon"><%= link_to '', edit_event_path(event.id), class: "fas fa-edit" %></div>
          <div class="icon"><%= link_to '', event_path(event.id), method: :delete, class:"fa-solid fa-trash-can", data: {confirm: "Are you sure to cancel your event?"} %></div>
          </div>

        </div>
        </div>
      </div>
      <% end %>

<div class="icon-group">
          <div class="icon"><%= link_to '', new_event_path, class:'fa-solid fa-plus'%> New event</div>
   </div>

 <h5>Booking requests <i class="fa-solid fa-bullhorn"></i> for your events
      <% current_user.events.each do |event|  %>
        <% booking_request = event.bookings.select { |booking| !booking.status } %>
         <div class="events" data-event-id="<%= event.id %>" >
        <% booking_request.each do |request|  %>
          <%= render 'bookings/booking', booking: request, event: event %>
        <% end%>
        </div>
      <% end %>
        </div>


  </div>



  <div class="bookings-container <%= params[:classbook] %>" data-switch-tab-target="bookings">
  <h5>There are <%= current_user.bookings.count %> coming <%= 'booking'.pluralize(current_user.bookings.count) %><i class="fa-solid fa-bullhorn"></i></h5>
      <% current_user.bookings.each do |booking| %>
      <div class="dashboard-item">

        <div class="item-description">

        <div>
          <%  if booking.event.photo.key.nil? %>
            <%= image_tag "placeholder-image.png", crop: :fill,  class: "event-img-vertical-s" %>
          <% else  %>
            <%= cl_image_tag booking.event.photo.key, crop: :fill,  class: "event-img-vertical-s" %>
          <% end  %>
        </div>

        <div class="flex-group">
          <div>
            <div><h5><%= booking.event.event_name %></h5></div>
            <div><span><%= booking.event.sport %> with <%= booking.event.user.first_name%></span></div>
            <div><span><%= booking.event.date.strftime(' %m-%b-%Y (%a)') %><strong> · </strong>
            <%= booking.event.duration %><strong> · </strong><%= booking.event.level %></span></div>

            <div id="bookAccept" data-booking-id="<%= booking.event.id %>">
              <div class="dashboard-item" id="booking-<%= booking.id %>">
               <div class="small-line" id="confirmation-book"><%= booking.status ? 'status: booked' : 'status: pending'  %></div>
              </div>
            </div>

          </div>
          <div class="icon-group">
          <% chatroom_check = Chatroom.where(sender: booking.event.user, recepient: current_user).or(Chatroom.where(sender: current_user, recepient: booking.event.user)) %>
          <% if chatroom_check.empty?%>
          <div class="icon"><%= link_to '', chatrooms_path(chatroom: {recepient_id: booking.event.user.id}), method: :post, class:'fa-regular fa-message'%></div>
          <% else %>
          <div class="icon"><%= link_to '', chatroom_path(chatroom_check.first), class:'fa-regular fa-message'%></div>
          <% end %>
          <div class="icon"><%= link_to '', event_path(booking.event.id), class:'fa-solid fa-magnifying-glass'%></div>
          <div class="icon"><%= link_to '', booking_path(booking.id), method: :delete, class:"fa-solid fa-trash-can", data: {confirm: "Are you sure to cancel?"} %></div>
          </div>
        </div>
        </div>
      <% end %>
  <%# </div> %>

<div>