config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :chatrooms, only: [:show, :new, :create] do
    resources :messages, only: :create
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :events do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:edit, :update, :destroy]
  get 'dashboard', to: 'dashboard#dashboard'
  get 'conversations', to: 'conversations#conversations'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar sticky-top navbar-expand-sm navbar-light navbar-lewagon <%= yield(:navbar_class) %>" data-controller="navbar-search">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "Ball.png" %>
  <% end %>

   <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-link email">
           Welcome <%= current_user.first_name %>
          </li>

          <li>
          <div class="search-form-control-nav">
              <%= form_tag events_path, method: :get do %>

                <%= text_field_tag :sports,
                params[:sports],
                class: "navbar-search d-none",
                "data-navbar-search-target": "searchbox",
                placeholder: "Find a sport"
                %>
                <%= submit_tag "Search", class:"d-none"%>
              <% end %>
            </form>
          </div>
          </li>
          <li class="nav-item active">
                <%= link_to '' do %>
                <i class="fa-solid fa-magnifying-glass" data-action="click->navbar-search#displaySearch" data-toggle="tooltip" data-placement="bottom" title="Search for a sport"></i>
                <% end %>
              </li>
          <li class="nav-item active">
            <%= link_to conversations_path do %>
            <i class="fa-regular fa-message" data-toggle="tooltip" data-placement="bottom" title="My messenger"></i>
            <% end %>
          </li>


          <li>
            <%= link_to dashboard_path({classbook:"d-none", classevent:"active", classeventtab: "active", classbooktab: " " }) do %>
            <i class="fa-regular fa-calendar" data-toggle="tooltip" data-placement="bottom" title="My dashboard"></i>
            <% end %>
          </li>
          <br>

          <li class="nav-item">

          </li>
          <li class="nav-item dropdown">
            <%  if current_user.photo.key.nil? %>
              <%= image_tag "default_profil.png", crop: :fill,  class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else  %>
              <%= cl_image_tag current_user.photo.key, crop: :fill,  class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end  %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Add new event", new_event_path , class: "dropdown-item" %>
              <%= link_to "Contact player", new_chatroom_path , class: "dropdown-item" %>
              <%= link_to "Dashboard", dashboard_path({classbook:"d-none", classevent:"active", classeventtab: "active", classbooktab: " " }), class: "dropdown-item" %>
              <%= link_to "Update your profile", edit_user_registration_path , class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>